# Generated by Django 5.1.1 on 2024-09-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name_plural': 'Transaction History'},
        ),
    ]
